packages:
  - 'app-*'
  - 'package-*'

allowBuilds:
  esbuild: true
  sharp: true
  vue-demi: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
