/**
 * 代码生成脚本（幂等可重复运行）
 *
 * 扫描 src/ 自动维护：
 *   1. src/index.ts                     —— barrel re-exports
 *   2. package.json 的 exports 字段      —— 子路径导出
 *   3. registry.json                    —— shadcn registry 条目
 *   4. ../app-ui-docs/src/App.tsx       —— 响应式布局（桌面侧栏 + 窄屏 Sheet 抽屉）+ 路由树
 *   5. ../app-ui-docs/src/routes/*.tsx   —— 每个组件一个文档页
 *   6. ../app-ui-docs/src/routes/index.tsx —— 首页：渲染 lib-ui-react/README.md + 分组组件一览
 *   7. ../app-ui-docs/src/components/component-groups.ts —— 组件分组数据（已定制/自定义/原版）
 *   8. ../app-ui-docs/src/demos/registry.ts  —— 已存在 demo 的懒加载映射
 *
 * 运行：pnpm --filter @akagiyui/ui-react gen
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const LIB = resolve(__dirname, "..");
const DOCS = resolve(LIB, "../app-ui-docs");

/** 自定义 block / 特殊条目，不参与自动 ui 扫描，registry.json 中原样保留 */
const BLOCK_NAMES = ["card-counter"];
/** 自定义 hook，registry.json 中保留手写项，不自动生成 hook 项 */
const SPECIAL_HOOKS = ["use-counter"];

// ---------- 组件分组 ----------
/**
 * 自定义组件：非 shadcn 官方组件、本库自研。
 * 判定依据：二者均不在批量导入 shadcn new-york 组件的提交（d060109）中，
 * 属后续自研产物。新增自研组件时把名字加到这里。
 */
const CUSTOM_COMPONENTS = new Set(["card-counter", "icons"]);
/**
 * 手动维护的「已定制」清单：源码有实质改动、但无法自动识别。
 * 自动识别规则：导入 `./icons`（Iconify 图标封装，官方 shadcn 用 lucide-react）。
 * 当前仅 button —— 基类追加了 `cursor-pointer`（见 lib-ui-react README 差异第 7 条）。
 */
const CUSTOMIZED_OVERRIDES = new Set(["button"]);
/** 自动识别「已定制」：从 `./icons` 导入图标，说明已接入 Iconify 图标方案 */
const CUSTOMIZED_IMPORT_RE = /from\s+["']\.\/icons["']/;

/** 分组元信息（顺序即展示顺序：已定制 → 自定义 → 原版） */
const GROUPS = {
  customized: {
    key: "customized",
    title: "已定制",
    badge: "已定制",
    description: "基于 shadcn 官方组件改编，与原版不同（Iconify 图标方案、cursor-pointer 等）。",
    cardDesc: "已适配本库定制（Iconify 图标方案等），与官方 shadcn 不同。",
  },
  custom: {
    key: "custom",
    title: "自定义",
    badge: "自定义",
    description: "非 shadcn 官方组件，本库自研。",
    cardDesc: "本库自研组件，不在官方 shadcn 中。",
  },
  original: {
    key: "original",
    title: "原版",
    badge: "原版",
    description: "与官方 shadcn new-york 组件一致（仅作相对路径改写）。",
    cardDesc: "shadcn new-york 原版组件。",
  },
};

/** 判定组件所属分组：custom(自定义) > customized(已定制) > original(原版) */
function classifyGroup(name) {
  if (CUSTOM_COMPONENTS.has(name)) return "custom";
  const src = read(join(LIB, `src/components/ui/${name}.tsx`));
  if (CUSTOMIZED_OVERRIDES.has(name) || CUSTOMIZED_IMPORT_RE.test(src)) return "customized";
  return "original";
}

const PEER_DEPS = new Set(["react", "react-dom"]);

// ---------- 工具函数 ----------
function read(path) {
  return readFileSync(path, "utf8");
}
function write(path, content) {
  writeFileSync(path, content + "\n", "utf8");
}
function listFiles(dir, ext) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(ext))
    .map((f) => f.slice(0, -ext.length))
    .sort((a, b) => a.localeCompare(b));
}
/** alert-dialog -> AlertDialog */
function toPascal(name) {
  return name
    .split("-")
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}
/** 扫描文件的所有 import 来源 */
function parseImports(file) {
  const content = read(file);
  const out = [];
  const re = /from\s+["']([^"']+)["']/g;
  let m;
  while ((m = re.exec(content)) !== null) out.push(m[1]);
  return out;
}
/** 拆分为 npm 依赖与 registry 依赖 */
function classify(specifiers) {
  const npm = new Set();
  const reg = new Set();
  for (const s of specifiers) {
    if (s.startsWith("@/")) {
      if (s === "@/lib/utils") {
        reg.add("utils");
      } else if (s.startsWith("@/components/ui/")) {
        reg.add(s.slice("@/components/ui/".length));
      } else if (s.startsWith("@/hooks/")) {
        reg.add(s.slice("@/hooks/".length));
      }
    } else if (s.startsWith(".")) {
      // 相对路径（当前源码风格）：./button、../hooks/use-mobile、../../lib/utils
      const rel = s.replace(/^(\.\.?\/)+/, "");
      if (rel.startsWith("lib/")) {
        reg.add(rel.slice("lib/".length));
      } else if (rel.startsWith("hooks/")) {
        reg.add(rel.slice("hooks/".length));
      } else {
        reg.add(rel);
      }
    } else if (!PEER_DEPS.has(s)) {
      npm.add(s);
    }
  }
  return { npm: [...npm].sort(), reg: [...reg].sort() };
}

// ---------- 1. 扫描组件/钩子 ----------
const uiComponents = listFiles(join(LIB, "src/components/ui"), ".tsx")
  .filter((n) => !BLOCK_NAMES.includes(n));
const allUiForExport = listFiles(join(LIB, "src/components/ui"), ".tsx"); // 包含 card-counter，用于 index/exports
const hooks = listFiles(join(LIB, "src/hooks"), ".ts");
const libs = listFiles(join(LIB, "src/lib"), ".ts");

// ---------- 2. 生成 src/index.ts ----------
function genIndex() {
  const lines = [
    "/**",
    " * AUTO-GENERATED by scripts/gen.mjs — 请勿手动编辑。",
    " * 运行 `pnpm --filter @akagiyui/ui-react gen` 重新生成。",
    " */",
    "",
  ];
  for (const name of allUiForExport) {
    lines.push(`export * from "./components/ui/${name}";`);
  }
  for (const h of hooks) lines.push(`export * from "./hooks/${h}";`);
  for (const l of libs) lines.push(`export * from "./lib/${l}";`);
  return lines.join("\n");
}

// ---------- 3. 生成 package.json exports ----------
/**
 * 直接指向源码（tsx/ts），配合「源码即产物」的消费方式（见 2aca76c 起的约定）：
 * workspace/文档站直接消费源码，无需先跑 tsdown 构建。
 */
function genExports() {
  const exp = {
    ".": {
      types: "./src/index.ts",
      import: "./src/index.ts",
    },
    "./styles.css": "./src/styles.css",
  };
  for (const name of allUiForExport) {
    exp[`./${name}`] = {
      types: `./src/components/ui/${name}.tsx`,
      import: `./src/components/ui/${name}.tsx`,
    };
  }
  for (const h of hooks) {
    exp[`./${h}`] = {
      types: `./src/hooks/${h}.ts`,
      import: `./src/hooks/${h}.ts`,
    };
  }
  for (const l of libs) {
    exp[`./${l}`] = {
      types: `./src/lib/${l}.ts`,
      import: `./src/lib/${l}.ts`,
    };
  }
  return exp;
}

// ---------- 4. 生成 registry.json ----------
function genRegistryItems() {
  const items = [];
  // utils (lib) —— 特殊
  items.push({
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    name: "utils",
    type: "registry:lib",
    title: "Utils",
    description: "Tailwind class merge utility (cn) using clsx and tailwind-merge.",
    files: [{ path: "src/lib/utils.ts", type: "registry:lib" }],
    dependencies: ["clsx", "tailwind-merge"],
  });

  // 自动 ui 组件
  for (const name of uiComponents) {
    const { npm, reg } = classify(parseImports(join(LIB, `src/components/ui/${name}.tsx`)));
    const item = {
      $schema: "https://ui.shadcn.com/schema/registry-item.json",
      name,
      type: "registry:ui",
      title: toPascal(name),
      description: `shadcn ${toPascal(name)} component (new-york).`,
      files: [{ path: `src/components/ui/${name}.tsx`, type: "registry:ui" }],
    };
    if (npm.length) item.dependencies = npm;
    if (reg.length) item.registryDependencies = reg;
    items.push(item);
  }

  // card-counter (block) —— 特殊
  items.push({
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    name: "card-counter",
    type: "registry:block",
    title: "Card Counter",
    description: "A card component with a built-in counter, combining Button and useCounter.",
    files: [{ path: "src/components/ui/card-counter.tsx", type: "registry:component" }],
    registryDependencies: ["button", "use-counter"],
  });

  // use-counter (hook) —— 特殊
  items.push({
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    name: "use-counter",
    type: "registry:hook",
    title: "useCounter",
    description: "A simple counter hook with increment, decrement, and reset actions.",
    files: [{ path: "src/hooks/use-counter.ts", type: "registry:hook" }],
  });

  // 其余自动 hook（如 use-mobile）
  for (const h of hooks.filter((n) => !SPECIAL_HOOKS.includes(n))) {
    const { npm, reg } = classify(parseImports(join(LIB, `src/hooks/${h}.ts`)));
    const item = {
      $schema: "https://ui.shadcn.com/schema/registry-item.json",
      name: h,
      type: "registry:hook",
      title: toPascal(h),
      description: `shadcn ${toPascal(h)} hook.`,
      files: [{ path: `src/hooks/${h}.ts`, type: "registry:hook" }],
    };
    if (npm.length) item.dependencies = npm;
    if (reg.length) item.registryDependencies = reg;
    items.push(item);
  }
  return items;
}

// ---------- 5. 生成 app-ui-docs 路由 ----------
function genRouteFile(name) {
  const Pascal = toPascal(name);
  return [
    "/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */",
    `import { DemoRenderer } from "../components/demo-renderer";`,
    `import { CodeBlock } from "../components/code-block";`,
    `import source from "../../../lib-ui-react/src/components/ui/${name}.tsx?raw";`,
    "",
    `export function ${Pascal}Page() {`,
    `  return (`,
    `    <div className="space-y-8">`,
    `      <div>`,
    `        <h1 className="text-2xl font-bold">${toPascal(name)}</h1>`,
    `        <p className="mt-1 text-sm text-muted-foreground">`,
    `          registry:ui · shadcn new-york 组件，支持 <code>npx shadcn add</code> 拉取。`,
    `        </p>`,
    `      </div>`,
    `      <section className="space-y-3">`,
    `        <h2 className="text-lg font-semibold">预览</h2>`,
    `        <div className="rounded-lg border bg-card p-6 text-card-foreground">`,
    `          <DemoRenderer name="${name}" />`,
    `        </div>`,
    `      </section>`,
    `      <section className="space-y-3">`,
    `        <h2 className="text-lg font-semibold">源码</h2>`,
    `        <CodeBlock code={source} />`,
    `      </section>`,
    `      <section className="space-y-3">`,
    `        <h2 className="text-lg font-semibold">安装</h2>`,
    `        <CodeBlock code={"npx shadcn@latest add @akagiyui/${name}"} lang="bash" />`,
    `      </section>`,
    `    </div>`,
    `  );`,
    `}`,
  ].join("\n");
}

function genIndexRoute() {
  return [
    "/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */",
    `import { Markdown } from "../components/markdown";`,
    `import { ComponentGrid } from "../components/component-grid";`,
    `import { componentGroups } from "../components/component-groups";`,
    `import readme from "../../../lib-ui-react/README.md?raw";`,
    "",
    `export function IndexPage() {`,
    `  return (`,
    `    <div className="space-y-10">`,
    `      <Markdown content={readme} />`,
    `      <ComponentGrid groups={componentGroups} />`,
    `    </div>`,
    `  );`,
    `}`,
  ].join("\n");
}

/** 生成分组数据：供侧栏导航与首页卡片网格共用 */
function genComponentGroups() {
  const groups = ["customized", "custom", "original"].map((key) => {
    const meta = GROUPS[key];
    return {
      title: meta.title,
      badge: meta.badge,
      description: meta.description,
      cardDesc: meta.cardDesc,
      items: allUiForExport.filter((n) => classifyGroup(n) === key).sort((a, b) => a.localeCompare(b)),
    };
  });
  const body = groups
    .map(
      (g) =>
        `  {\n` +
        `    title: ${JSON.stringify(g.title)},\n` +
        `    badge: ${JSON.stringify(g.badge)},\n` +
        `    description: ${JSON.stringify(g.description)},\n` +
        `    cardDesc: ${JSON.stringify(g.cardDesc)},\n` +
        `    items: ${JSON.stringify(g.items)},\n` +
        `  }`
    )
    .join(",\n");
  return [
    "/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */",
    "",
    `export type ComponentGroup = {`,
    `  /** 分组标题 */`,
    `  title: string;`,
    `  /** 卡片徽标文字 */`,
    `  badge: string;`,
    `  /** 分组说明（侧栏/首页标题下方） */`,
    `  description: string;`,
    `  /** 卡片描述 */`,
    `  cardDesc: string;`,
    `  /** 组件名列表（即路由名） */`,
    `  items: string[];`,
    `};`,
    "",
    `export const componentGroups: ComponentGroup[] = [`,
    body,
    `];`,
  ].join("\n");
}

function genApp() {
  const imports = allUiForExport
    .map((n) => `import { ${toPascal(n)}Page } from "./routes/${n}";`)
    .join("\n");
  const routes = allUiForExport
    .map(
      (n) =>
        `const ${toPascal(n)}Route = createRoute({\n  getParentRoute: () => rootRoute,\n  path: "/${n}",\n  component: ${toPascal(n)}Page,\n});`
    )
    .join("\n\n");
  const addChildren = allUiForExport.map((n) => `${toPascal(n)}Route`).join(",\n  ");
  return [
    "/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */",
    `import { useState } from "react";`,
    `import {`,
    `  createRootRoute,`,
    `  createRoute,`,
    `  createRouter,`,
    `  Outlet,`,
    `} from "@tanstack/react-router";`,
    `import {`,
    `  Toaster,`,
    `  Button,`,
    `  Sheet,`,
    `  SheetContent,`,
    `  SheetHeader,`,
    `  SheetTitle,`,
    `  SheetTrigger,`,
    `  PanelLeftIcon,`,
    `} from "@akagiyui/ui-react";`,
    `import { ThemeToggle } from "./components/theme-toggle";`,
    `import { SidebarNav } from "./components/sidebar-nav";`,
    `import { IndexPage } from "./routes/index";`,
    imports,
    "",
    `function RootLayout() {`,
    `  const [navOpen, setNavOpen] = useState(false);`,
    `  return (`,
    `    <div className="min-h-screen bg-background text-foreground">`,
    `      <div className="lg:flex">`,
    `        {/* 桌面侧栏（lg+ 显示，窄屏走 Sheet 抽屉） */}`,
    `        <aside className="sticky top-0 hidden h-screen w-56 shrink-0 overflow-y-auto border-r p-4 lg:block">`,
    `          <SidebarNav />`,
    `        </aside>`,
    `        <div className="flex min-w-0 flex-1 flex-col">`,
    `          <header className="sticky top-0 z-30 flex items-center justify-between gap-2 border-b bg-background/80 px-4 py-3 backdrop-blur lg:justify-end lg:px-8">`,
    `            <Sheet open={navOpen} onOpenChange={setNavOpen}>`,
    `              <SheetTrigger asChild>`,
    `                <Button`,
    `                  type="button"`,
    `                  variant="ghost"`,
    `                  size="icon"`,
    `                  aria-label="打开组件导航"`,
    `                  className="lg:hidden"`,
    `                >`,
    `                  <PanelLeftIcon />`,
    `                </Button>`,
    `              </SheetTrigger>`,
    `              <SheetContent side="left" className="w-72 gap-0 p-0">`,
    `                <SheetHeader className="border-b">`,
    `                  <SheetTitle>组件导航</SheetTitle>`,
    `                </SheetHeader>`,
    `                <div className="min-h-0 flex-1 overflow-y-auto p-4">`,
    `                  <SidebarNav onNavigate={() => setNavOpen(false)} />`,
    `                </div>`,
    `              </SheetContent>`,
    `            </Sheet>`,
    `            <span className="truncate text-sm font-semibold lg:hidden">`,
    `              @akagiyui/ui-react`,
    `            </span>`,
    `            <ThemeToggle />`,
    `          </header>`,
    `          <main className="mx-auto w-full max-w-5xl px-4 py-6 sm:px-6 lg:py-10">`,
    `            <Outlet />`,
    `          </main>`,
    `        </div>`,
    `      </div>`,
    `      <Toaster richColors position="bottom-right" />`,
    `    </div>`,
    `  );`,
    `}`,
    "",
    `const rootRoute = createRootRoute({`,
    `  component: RootLayout,`,
    `});`,
    "",
    `const indexRoute = createRoute({`,
    `  getParentRoute: () => rootRoute,`,
    `  path: "/",`,
    `  component: IndexPage,`,
    `});`,
    "",
    routes,
    "",
    `const routeTree = rootRoute.addChildren([`,
    `  indexRoute,`,
    `  ${addChildren},`,
    `]);`,
    "",
    `export const router = createRouter({ routeTree });`,
    "",
    `declare module "@tanstack/react-router" {`,
    `  interface Register {`,
    `    router: typeof router;`,
    `  }`,
    `}`,
  ].join("\n");
}

// ---------- 6. 生成 demos/registry.ts ----------
function genDemosRegistry() {
  const demos = listFiles(join(DOCS, "src/demos"), ".tsx");
  const entries = demos
    .map((n) => `  "${n}": lazy(() => import("./${n}")),`)
    .join("\n");
  return [
    "/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */",
    `import { lazy } from "react";`,
    "",
    `export const demos: Record<string, ReturnType<typeof lazy>> = {`,
    entries,
    `};`,
  ].join("\n");
}

// ---------- 执行 ----------
function main() {
  // lib: index.ts
  write(join(LIB, "src/index.ts"), genIndex());
  console.log("✔ src/index.ts");

  // lib: package.json exports
  const pkgPath = join(LIB, "package.json");
  const pkg = JSON.parse(read(pkgPath));
  pkg.exports = genExports();
  write(pkgPath, JSON.stringify(pkg, null, 2));
  console.log("✔ package.json exports");

  // lib: registry.json
  const registry = {
    $schema: "https://ui.shadcn.com/schema/registry.json",
    name: "@akagiyui/ui-react",
    homepage: "https://github.com/AkagiYui/js-together",
    items: genRegistryItems(),
  };
  write(join(LIB, "registry.json"), JSON.stringify(registry, null, 2));
  console.log("✔ registry.json");

  // docs: routes
  const routesDir = join(DOCS, "src/routes");
  mkdirSync(routesDir, { recursive: true });
  write(join(routesDir, "index.tsx"), genIndexRoute());
  for (const name of allUiForExport) {
    write(join(routesDir, `${name}.tsx`), genRouteFile(name));
  }
  console.log(`✔ docs routes (${allUiForExport.length} pages)`);

  // docs: component-groups.ts（分组数据）
  const componentsDir = join(DOCS, "src/components");
  mkdirSync(componentsDir, { recursive: true });
  write(join(componentsDir, "component-groups.ts"), genComponentGroups());
  console.log("✔ docs component-groups.ts");

  // docs: App.tsx
  write(join(DOCS, "src/App.tsx"), genApp());
  console.log("✔ docs App.tsx");

  // docs: demos/registry.ts
  const demosDir = join(DOCS, "src/demos");
  mkdirSync(demosDir, { recursive: true });
  write(join(demosDir, "registry.ts"), genDemosRegistry());
  console.log("✔ docs demos/registry.ts");
}

main();