/**
 * 代码生成脚本（幂等可重复运行）
 *
 * 扫描 src/ 自动维护：
 *   1. src/index.ts                     —— barrel re-exports
 *   2. package.json 的 exports 字段      —— 子路径导出
 *   3. registry.json                    —— shadcn registry 条目
 *   4. ../app-ui-docs/src/App.tsx       —— 侧栏布局 + 路由树
 *   5. ../app-ui-docs/src/routes/*.tsx   —— 每个组件一个文档页
 *   6. ../app-ui-docs/src/routes/index.tsx —— 组件总览
 *   7. ../app-ui-docs/src/demos/registry.ts  —— 已存在 demo 的懒加载映射
 *
 * 运行：pnpm --filter @akagiyui/ui-react gen
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const LIB = resolve(__dirname, "..");
const DOCS = resolve(LIB, "../app-ui-docs");

/** 自定义 block / 特殊条目，不参与自动 ui 扫描，registry.json 中原样保留 */
const BLOCK_NAMES = ["card-counter"];
/** 自定义 hook，registry.json 中保留手写项，不自动生成 hook 项 */
const SPECIAL_HOOKS = ["use-counter"];

const PEER_DEPS = new Set(["react", "react-dom"]);

// ---------- 工具函数 ----------
function read(path) {
  return readFileSync(path, "utf8");
}
function write(path, content) {
  writeFileSync(path, content + "\n", "utf8");
}
function listFiles(dir, ext) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(ext))
    .map((f) => f.slice(0, -ext.length))
    .sort((a, b) => a.localeCompare(b));
}
/** alert-dialog -> AlertDialog */
function toPascal(name) {
  return name
    .split("-")
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}
/** 扫描文件的所有 import 来源 */
function parseImports(file) {
  const content = read(file);
  const out = [];
  const re = /from\s+["']([^"']+)["']/g;
  let m;
  while ((m = re.exec(content)) !== null) out.push(m[1]);
  return out;
}
/** 拆分为 npm 依赖与 registry 依赖 */
function classify(specifiers) {
  const npm = new Set();
  const reg = new Set();
  for (const s of specifiers) {
    if (s.startsWith("@/")) {
      if (s === "@/lib/utils") {
        reg.add("utils");
      } else if (s.startsWith("@/components/ui/")) {
        reg.add(s.slice("@/components/ui/".length));
      } else if (s.startsWith("@/hooks/")) {
        reg.add(s.slice("@/hooks/".length));
      }
    } else if (s.startsWith(".")) {
      // 相对路径，忽略
    } else if (!PEER_DEPS.has(s)) {
      npm.add(s);
    }
  }
  return { npm: [...npm].sort(), reg: [...reg].sort() };
}

// ---------- 1. 扫描组件/钩子 ----------
const uiComponents = listFiles(join(LIB, "src/components/ui"), ".tsx")
  .filter((n) => !BLOCK_NAMES.includes(n));
const allUiForExport = listFiles(join(LIB, "src/components/ui"), ".tsx"); // 包含 card-counter，用于 index/exports
const hooks = listFiles(join(LIB, "src/hooks"), ".ts");
const libs = listFiles(join(LIB, "src/lib"), ".ts");

// ---------- 2. 生成 src/index.ts ----------
function genIndex() {
  const lines = [
    "/**",
    " * AUTO-GENERATED by scripts/gen.mjs — 请勿手动编辑。",
    " * 运行 `pnpm --filter @akagiyui/ui-react gen` 重新生成。",
    " */",
    "",
  ];
  for (const name of allUiForExport) {
    lines.push(`export * from "./components/ui/${name}";`);
  }
  for (const h of hooks) lines.push(`export * from "./hooks/${h}";`);
  for (const l of libs) lines.push(`export * from "./lib/${l}";`);
  return lines.join("\n");
}

// ---------- 3. 生成 package.json exports ----------
function genExports() {
  const exp = {
    ".": {
      types: "./dist/index.d.mts",
      import: "./dist/index.mjs",
    },
    "./styles.css": "./src/styles.css",
  };
  for (const name of allUiForExport) {
    exp[`./${name}`] = {
      types: `./dist/components/ui/${name}.d.mts`,
      import: `./dist/components/ui/${name}.mjs`,
    };
  }
  for (const h of hooks) {
    exp[`./${h}`] = {
      types: `./dist/hooks/${h}.d.mts`,
      import: `./dist/hooks/${h}.mjs`,
    };
  }
  for (const l of libs) {
    exp[`./${l}`] = {
      types: `./dist/lib/${l}.d.mts`,
      import: `./dist/lib/${l}.mjs`,
    };
  }
  return exp;
}

// ---------- 4. 生成 registry.json ----------
function genRegistryItems() {
  const items = [];
  // utils (lib) —— 特殊
  items.push({
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    name: "utils",
    type: "registry:lib",
    title: "Utils",
    description: "Tailwind class merge utility (cn) using clsx and tailwind-merge.",
    files: [{ path: "src/lib/utils.ts", type: "registry:lib" }],
    dependencies: ["clsx", "tailwind-merge"],
  });

  // 自动 ui 组件
  for (const name of uiComponents) {
    const { npm, reg } = classify(parseImports(join(LIB, `src/components/ui/${name}.tsx`)));
    const item = {
      $schema: "https://ui.shadcn.com/schema/registry-item.json",
      name,
      type: "registry:ui",
      title: toPascal(name),
      description: `shadcn ${toPascal(name)} component (new-york).`,
      files: [{ path: `src/components/ui/${name}.tsx`, type: "registry:ui" }],
    };
    if (npm.length) item.dependencies = npm;
    if (reg.length) item.registryDependencies = reg;
    items.push(item);
  }

  // card-counter (block) —— 特殊
  items.push({
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    name: "card-counter",
    type: "registry:block",
    title: "Card Counter",
    description: "A card component with a built-in counter, combining Button and useCounter.",
    files: [{ path: "src/components/ui/card-counter.tsx", type: "registry:component" }],
    registryDependencies: ["button", "use-counter"],
  });

  // use-counter (hook) —— 特殊
  items.push({
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    name: "use-counter",
    type: "registry:hook",
    title: "useCounter",
    description: "A simple counter hook with increment, decrement, and reset actions.",
    files: [{ path: "src/hooks/use-counter.ts", type: "registry:hook" }],
  });

  // 其余自动 hook（如 use-mobile）
  for (const h of hooks.filter((n) => !SPECIAL_HOOKS.includes(n))) {
    const { npm, reg } = classify(parseImports(join(LIB, `src/hooks/${h}.ts`)));
    const item = {
      $schema: "https://ui.shadcn.com/schema/registry-item.json",
      name: h,
      type: "registry:hook",
      title: toPascal(h),
      description: `shadcn ${toPascal(h)} hook.`,
      files: [{ path: `src/hooks/${h}.ts`, type: "registry:hook" }],
    };
    if (npm.length) item.dependencies = npm;
    if (reg.length) item.registryDependencies = reg;
    items.push(item);
  }
  return items;
}

// ---------- 5. 生成 app-ui-docs 路由 ----------
function genRouteFile(name) {
  const Pascal = toPascal(name);
  return [
    "/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */",
    `import { DemoRenderer } from "../components/demo-renderer";`,
    `import source from "../../../lib-ui-react/src/components/ui/${name}.tsx?raw";`,
    "",
    `export function ${Pascal}Page() {`,
    `  return (`,
    `    <div className="space-y-8">`,
    `      <div>`,
    `        <h1 className="text-2xl font-bold">${toPascal(name)}</h1>`,
    `        <p className="mt-1 text-sm text-muted-foreground">`,
    `          registry:ui · shadcn new-york 组件，支持 <code>npx shadcn add</code> 拉取。`,
    `        </p>`,
    `      </div>`,
    `      <section className="space-y-3">`,
    `        <h2 className="text-lg font-semibold">预览</h2>`,
    `        <div className="rounded-lg border bg-card p-6 text-card-foreground">`,
    `          <DemoRenderer name="${name}" />`,
    `        </div>`,
    `      </section>`,
    `      <section className="space-y-3">`,
    `        <h2 className="text-lg font-semibold">源码</h2>`,
    `        <pre className="overflow-x-auto rounded-lg bg-muted p-4 text-sm text-muted-foreground">`,
    `          <code>{source}</code>`,
    `        </pre>`,
    `      </section>`,
    `      <section className="space-y-3">`,
    `        <h2 className="text-lg font-semibold">安装</h2>`,
    `        <code className="block rounded-lg bg-muted p-4 text-sm text-muted-foreground">`,
    `          npx shadcn@latest add @akagiyui/${name}`,
    `        </code>`,
    `      </section>`,
    `    </div>`,
    `  );`,
    `}`,
  ].join("\n");
}

function genIndexRoute() {
  const cards = allUiForExport
    .map(
      (name) =>
        `      <Link\n        key="${name}"\n        to="/${name}"\n        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"\n      >\n        <div className="flex items-center justify-between">\n          <h2 className="text-lg font-semibold">${toPascal(name)}</h2>\n          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>\n        </div>\n        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>\n        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/${name}</code>\n      </Link>`
    )
    .join("\n");
  return [
    "/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */",
    `import { Link } from "@tanstack/react-router";`,
    "",
    `export function IndexPage() {`,
    `  return (`,
    `    <div className="space-y-8">`,
    `      <div>`,
    `        <h1 className="text-3xl font-bold text-foreground">@akagiyui/ui-react</h1>`,
    `        <p className="mt-2 text-muted-foreground">`,
    `          基于 shadcn (new-york) 的个人 React 组件库。支持 npm 包与 registry 双模消费。`,
    `        </p>`,
    `      </div>`,
    `      <div className="grid gap-4 sm:grid-cols-2">`,
    cards,
    `      </div>`,
    `    </div>`,
    `  );`,
    `}`,
  ].join("\n");
}

function genApp() {
  const imports = allUiForExport
    .map((n) => `import { ${toPascal(n)}Page } from "./routes/${n}";`)
    .join("\n");
  const routes = allUiForExport
    .map(
      (n) =>
        `const ${toPascal(n)}Route = createRoute({\n  getParentRoute: () => rootRoute,\n  path: "/${n}",\n  component: ${toPascal(n)}Page,\n});`
    )
    .join("\n\n");
  const addChildren = allUiForExport.map((n) => `${toPascal(n)}Route`).join(",\n  ");
  const navLinks = allUiForExport
    .map(
      (n) =>
        `            <Link\n              key="${n}"\n              to={\`/${n}\`}\n              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"\n              activeProps={{ className: "bg-accent text-foreground" }}\n            >\n              ${n}\n            </Link>`
    )
    .join("\n");
  return [
    "/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */",
    `import {`,
    `  createRootRoute,`,
    `  createRoute,`,
    `  createRouter,`,
    `  Outlet,`,
    `  Link,`,
    `} from "@tanstack/react-router";`,
    `import { Toaster } from "@akagiyui/ui-react";`,
    `import { ThemeToggle } from "./components/theme-toggle";`,
    `import { IndexPage } from "./routes/index";`,
    imports,
    "",
    `const rootRoute = createRootRoute({`,
    `  component: () => (`,
    `    <div className="min-h-screen bg-background text-foreground">`,
    `      <div className="flex">`,
    `        <aside className="sticky top-0 h-screen w-56 shrink-0 overflow-y-auto border-r p-4">`,
    `          <Link to="/" className="text-base font-semibold text-foreground">`,
    `            @akagiyui/ui-react`,
    `          </Link>`,
    `          <nav className="mt-4 flex flex-col gap-0.5 text-sm">`,
    navLinks,
    `          </nav>`,
    `        </aside>`,
    `        <div className="flex-1 min-w-0">`,
    `          <header className="flex items-center justify-end border-b px-6 py-3">`,
    `            <ThemeToggle />`,
    `          </header>`,
    `          <main className="mx-auto max-w-5xl px-6 py-10">`,
    `            <Outlet />`,
    `          </main>`,
    `        </div>`,
    `      </div>`,
    `      <Toaster richColors position="bottom-right" />`,
    `    </div>`,
    `  ),`,
    `});`,
    "",
    `const indexRoute = createRoute({`,
    `  getParentRoute: () => rootRoute,`,
    `  path: "/",`,
    `  component: IndexPage,`,
    `});`,
    "",
    routes,
    "",
    `const routeTree = rootRoute.addChildren([`,
    `  indexRoute,`,
    `  ${addChildren},`,
    `]);`,
    "",
    `export const router = createRouter({ routeTree });`,
    "",
    `declare module "@tanstack/react-router" {`,
    `  interface Register {`,
    `    router: typeof router;`,
    `  }`,
    `}`,
  ].join("\n");
}

// ---------- 6. 生成 demos/registry.ts ----------
function genDemosRegistry() {
  const demos = listFiles(join(DOCS, "src/demos"), ".tsx");
  const entries = demos
    .map((n) => `  "${n}": lazy(() => import("./${n}")),`)
    .join("\n");
  return [
    "/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */",
    `import { lazy } from "react";`,
    "",
    `export const demos: Record<string, ReturnType<typeof lazy>> = {`,
    entries,
    `};`,
  ].join("\n");
}

// ---------- 执行 ----------
function main() {
  // lib: index.ts
  write(join(LIB, "src/index.ts"), genIndex());
  console.log("✔ src/index.ts");

  // lib: package.json exports
  const pkgPath = join(LIB, "package.json");
  const pkg = JSON.parse(read(pkgPath));
  pkg.exports = genExports();
  write(pkgPath, JSON.stringify(pkg, null, 2));
  console.log("✔ package.json exports");

  // lib: registry.json
  const registry = {
    $schema: "https://ui.shadcn.com/schema/registry.json",
    name: "@akagiyui/ui-react",
    homepage: "https://github.com/AkagiYui/js-together",
    items: genRegistryItems(),
  };
  write(join(LIB, "registry.json"), JSON.stringify(registry, null, 2));
  console.log("✔ registry.json");

  // docs: routes
  const routesDir = join(DOCS, "src/routes");
  mkdirSync(routesDir, { recursive: true });
  write(join(routesDir, "index.tsx"), genIndexRoute());
  for (const name of allUiForExport) {
    write(join(routesDir, `${name}.tsx`), genRouteFile(name));
  }
  console.log(`✔ docs routes (${allUiForExport.length} pages)`);

  // docs: App.tsx
  write(join(DOCS, "src/App.tsx"), genApp());
  console.log("✔ docs App.tsx");

  // docs: demos/registry.ts
  const demosDir = join(DOCS, "src/demos");
  mkdirSync(demosDir, { recursive: true });
  write(join(demosDir, "registry.ts"), genDemosRegistry());
  console.log("✔ docs demos/registry.ts");
}

main();