/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */

export type ComponentGroup = {
  /** 分组标题 */
  title: string;
  /** 卡片徽标文字 */
  badge: string;
  /** 分组说明（侧栏/首页标题下方） */
  description: string;
  /** 卡片描述 */
  cardDesc: string;
  /** 组件名列表（即路由名） */
  items: string[];
};

export const componentGroups: ComponentGroup[] = [
  {
    title: "已定制",
    badge: "已定制",
    description: "基于 shadcn 官方组件改编，与原版不同（Iconify 图标方案、cursor-pointer 等）。",
    cardDesc: "已适配本库定制（Iconify 图标方案等），与官方 shadcn 不同。",
    items: ["accordion","breadcrumb","button","calendar","carousel","checkbox","combobox","command","context-menu","dialog","dropdown-menu","input-otp","menubar","message-scroller","native-select","navigation-menu","pagination","radio-group","resizable","select","sheet","sidebar","sonner","spinner"],
  },
  {
    title: "自定义",
    badge: "自定义",
    description: "非 shadcn 官方组件，本库自研。",
    cardDesc: "本库自研组件，不在官方 shadcn 中。",
    items: ["card-counter","icons"],
  },
  {
    title: "原版",
    badge: "原版",
    description: "与官方 shadcn new-york 组件一致（仅作相对路径改写）。",
    cardDesc: "shadcn new-york 原版组件。",
    items: ["alert","alert-dialog","aspect-ratio","attachment","avatar","badge","bubble","button-group","card","chart","collapsible","direction","drawer","empty","field","form","hover-card","input","input-group","item","kbd","label","marker","message","popover","progress","scroll-area","separator","skeleton","slider","switch","table","tabs","textarea","toggle","toggle-group","tooltip"],
  }
];
