/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */
import { useState } from "react";
import {
  createRootRoute,
  createRoute,
  createRouter,
  Outlet,
} from "@tanstack/react-router";
import {
  Toaster,
  Button,
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
  PanelLeftIcon,
} from "@akagiyui/ui-react";
import { ThemeToggle } from "./components/theme-toggle";
import { SidebarNav } from "./components/sidebar-nav";
import { IndexPage } from "./routes/index";
import { AccordionPage } from "./routes/accordion";
import { AlertPage } from "./routes/alert";
import { AlertDialogPage } from "./routes/alert-dialog";
import { AspectRatioPage } from "./routes/aspect-ratio";
import { AttachmentPage } from "./routes/attachment";
import { AvatarPage } from "./routes/avatar";
import { BadgePage } from "./routes/badge";
import { BreadcrumbPage } from "./routes/breadcrumb";
import { BubblePage } from "./routes/bubble";
import { ButtonPage } from "./routes/button";
import { ButtonGroupPage } from "./routes/button-group";
import { CalendarPage } from "./routes/calendar";
import { CardPage } from "./routes/card";
import { CardCounterPage } from "./routes/card-counter";
import { CarouselPage } from "./routes/carousel";
import { ChartPage } from "./routes/chart";
import { CheckboxPage } from "./routes/checkbox";
import { CollapsiblePage } from "./routes/collapsible";
import { ComboboxPage } from "./routes/combobox";
import { CommandPage } from "./routes/command";
import { ContextMenuPage } from "./routes/context-menu";
import { DialogPage } from "./routes/dialog";
import { DirectionPage } from "./routes/direction";
import { DrawerPage } from "./routes/drawer";
import { DropdownMenuPage } from "./routes/dropdown-menu";
import { EmptyPage } from "./routes/empty";
import { FieldPage } from "./routes/field";
import { FormPage } from "./routes/form";
import { HoverCardPage } from "./routes/hover-card";
import { IconsPage } from "./routes/icons";
import { InputPage } from "./routes/input";
import { InputGroupPage } from "./routes/input-group";
import { InputOtpPage } from "./routes/input-otp";
import { ItemPage } from "./routes/item";
import { KbdPage } from "./routes/kbd";
import { LabelPage } from "./routes/label";
import { MarkerPage } from "./routes/marker";
import { MenubarPage } from "./routes/menubar";
import { MessagePage } from "./routes/message";
import { MessageScrollerPage } from "./routes/message-scroller";
import { NativeSelectPage } from "./routes/native-select";
import { NavigationMenuPage } from "./routes/navigation-menu";
import { PaginationPage } from "./routes/pagination";
import { PopoverPage } from "./routes/popover";
import { ProgressPage } from "./routes/progress";
import { RadioGroupPage } from "./routes/radio-group";
import { ResizablePage } from "./routes/resizable";
import { ScrollAreaPage } from "./routes/scroll-area";
import { SelectPage } from "./routes/select";
import { SeparatorPage } from "./routes/separator";
import { SheetPage } from "./routes/sheet";
import { SidebarPage } from "./routes/sidebar";
import { SkeletonPage } from "./routes/skeleton";
import { SliderPage } from "./routes/slider";
import { SonnerPage } from "./routes/sonner";
import { SpinnerPage } from "./routes/spinner";
import { SwitchPage } from "./routes/switch";
import { TablePage } from "./routes/table";
import { TabsPage } from "./routes/tabs";
import { TextareaPage } from "./routes/textarea";
import { TogglePage } from "./routes/toggle";
import { ToggleGroupPage } from "./routes/toggle-group";
import { TooltipPage } from "./routes/tooltip";

function RootLayout() {
  const [navOpen, setNavOpen] = useState(false);
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="lg:flex">
        {/* 桌面侧栏（lg+ 显示，窄屏走 Sheet 抽屉） */}
        <aside className="sticky top-0 hidden h-screen w-56 shrink-0 overflow-y-auto border-r p-4 lg:block">
          <SidebarNav />
        </aside>
        <div className="flex min-w-0 flex-1 flex-col">
          <header className="sticky top-0 z-30 flex items-center justify-between gap-2 border-b bg-background/80 px-4 py-3 backdrop-blur lg:justify-end lg:px-8">
            <Sheet open={navOpen} onOpenChange={setNavOpen}>
              <SheetTrigger asChild>
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  aria-label="打开组件导航"
                  className="lg:hidden"
                >
                  <PanelLeftIcon />
                </Button>
              </SheetTrigger>
              <SheetContent side="left" className="w-72 gap-0 p-0">
                <SheetHeader className="border-b">
                  <SheetTitle>组件导航</SheetTitle>
                </SheetHeader>
                <div className="min-h-0 flex-1 overflow-y-auto p-4">
                  <SidebarNav onNavigate={() => setNavOpen(false)} />
                </div>
              </SheetContent>
            </Sheet>
            <span className="truncate text-sm font-semibold lg:hidden">
              @akagiyui/ui-react
            </span>
            <ThemeToggle />
          </header>
          <main className="mx-auto w-full max-w-5xl px-4 py-6 sm:px-6 lg:py-10">
            <Outlet />
          </main>
        </div>
      </div>
      <Toaster richColors position="bottom-right" />
    </div>
  );
}

const rootRoute = createRootRoute({
  component: RootLayout,
});

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/",
  component: IndexPage,
});

const AccordionRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/accordion",
  component: AccordionPage,
});

const AlertRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/alert",
  component: AlertPage,
});

const AlertDialogRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/alert-dialog",
  component: AlertDialogPage,
});

const AspectRatioRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/aspect-ratio",
  component: AspectRatioPage,
});

const AttachmentRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/attachment",
  component: AttachmentPage,
});

const AvatarRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/avatar",
  component: AvatarPage,
});

const BadgeRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/badge",
  component: BadgePage,
});

const BreadcrumbRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/breadcrumb",
  component: BreadcrumbPage,
});

const BubbleRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/bubble",
  component: BubblePage,
});

const ButtonRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/button",
  component: ButtonPage,
});

const ButtonGroupRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/button-group",
  component: ButtonGroupPage,
});

const CalendarRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/calendar",
  component: CalendarPage,
});

const CardRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/card",
  component: CardPage,
});

const CardCounterRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/card-counter",
  component: CardCounterPage,
});

const CarouselRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/carousel",
  component: CarouselPage,
});

const ChartRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/chart",
  component: ChartPage,
});

const CheckboxRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/checkbox",
  component: CheckboxPage,
});

const CollapsibleRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/collapsible",
  component: CollapsiblePage,
});

const ComboboxRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/combobox",
  component: ComboboxPage,
});

const CommandRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/command",
  component: CommandPage,
});

const ContextMenuRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/context-menu",
  component: ContextMenuPage,
});

const DialogRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/dialog",
  component: DialogPage,
});

const DirectionRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/direction",
  component: DirectionPage,
});

const DrawerRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/drawer",
  component: DrawerPage,
});

const DropdownMenuRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/dropdown-menu",
  component: DropdownMenuPage,
});

const EmptyRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/empty",
  component: EmptyPage,
});

const FieldRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/field",
  component: FieldPage,
});

const FormRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/form",
  component: FormPage,
});

const HoverCardRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/hover-card",
  component: HoverCardPage,
});

const IconsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/icons",
  component: IconsPage,
});

const InputRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/input",
  component: InputPage,
});

const InputGroupRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/input-group",
  component: InputGroupPage,
});

const InputOtpRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/input-otp",
  component: InputOtpPage,
});

const ItemRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/item",
  component: ItemPage,
});

const KbdRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/kbd",
  component: KbdPage,
});

const LabelRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/label",
  component: LabelPage,
});

const MarkerRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/marker",
  component: MarkerPage,
});

const MenubarRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/menubar",
  component: MenubarPage,
});

const MessageRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/message",
  component: MessagePage,
});

const MessageScrollerRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/message-scroller",
  component: MessageScrollerPage,
});

const NativeSelectRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/native-select",
  component: NativeSelectPage,
});

const NavigationMenuRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/navigation-menu",
  component: NavigationMenuPage,
});

const PaginationRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/pagination",
  component: PaginationPage,
});

const PopoverRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/popover",
  component: PopoverPage,
});

const ProgressRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/progress",
  component: ProgressPage,
});

const RadioGroupRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/radio-group",
  component: RadioGroupPage,
});

const ResizableRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/resizable",
  component: ResizablePage,
});

const ScrollAreaRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/scroll-area",
  component: ScrollAreaPage,
});

const SelectRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/select",
  component: SelectPage,
});

const SeparatorRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/separator",
  component: SeparatorPage,
});

const SheetRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/sheet",
  component: SheetPage,
});

const SidebarRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/sidebar",
  component: SidebarPage,
});

const SkeletonRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/skeleton",
  component: SkeletonPage,
});

const SliderRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/slider",
  component: SliderPage,
});

const SonnerRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/sonner",
  component: SonnerPage,
});

const SpinnerRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/spinner",
  component: SpinnerPage,
});

const SwitchRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/switch",
  component: SwitchPage,
});

const TableRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/table",
  component: TablePage,
});

const TabsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/tabs",
  component: TabsPage,
});

const TextareaRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/textarea",
  component: TextareaPage,
});

const ToggleRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/toggle",
  component: TogglePage,
});

const ToggleGroupRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/toggle-group",
  component: ToggleGroupPage,
});

const TooltipRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/tooltip",
  component: TooltipPage,
});

const routeTree = rootRoute.addChildren([
  indexRoute,
  AccordionRoute,
  AlertRoute,
  AlertDialogRoute,
  AspectRatioRoute,
  AttachmentRoute,
  AvatarRoute,
  BadgeRoute,
  BreadcrumbRoute,
  BubbleRoute,
  ButtonRoute,
  ButtonGroupRoute,
  CalendarRoute,
  CardRoute,
  CardCounterRoute,
  CarouselRoute,
  ChartRoute,
  CheckboxRoute,
  CollapsibleRoute,
  ComboboxRoute,
  CommandRoute,
  ContextMenuRoute,
  DialogRoute,
  DirectionRoute,
  DrawerRoute,
  DropdownMenuRoute,
  EmptyRoute,
  FieldRoute,
  FormRoute,
  HoverCardRoute,
  IconsRoute,
  InputRoute,
  InputGroupRoute,
  InputOtpRoute,
  ItemRoute,
  KbdRoute,
  LabelRoute,
  MarkerRoute,
  MenubarRoute,
  MessageRoute,
  MessageScrollerRoute,
  NativeSelectRoute,
  NavigationMenuRoute,
  PaginationRoute,
  PopoverRoute,
  ProgressRoute,
  RadioGroupRoute,
  ResizableRoute,
  ScrollAreaRoute,
  SelectRoute,
  SeparatorRoute,
  SheetRoute,
  SidebarRoute,
  SkeletonRoute,
  SliderRoute,
  SonnerRoute,
  SpinnerRoute,
  SwitchRoute,
  TableRoute,
  TabsRoute,
  TextareaRoute,
  ToggleRoute,
  ToggleGroupRoute,
  TooltipRoute,
]);

export const router = createRouter({ routeTree });

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
