/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */
import {
  createRootRoute,
  createRoute,
  createRouter,
  Outlet,
  Link,
} from "@tanstack/react-router";
import { Toaster } from "@akagiyui/ui-react";
import { ThemeToggle } from "./components/theme-toggle";
import { IndexPage } from "./routes/index";
import { AccordionPage } from "./routes/accordion";
import { AlertPage } from "./routes/alert";
import { AlertDialogPage } from "./routes/alert-dialog";
import { AspectRatioPage } from "./routes/aspect-ratio";
import { AttachmentPage } from "./routes/attachment";
import { AvatarPage } from "./routes/avatar";
import { BadgePage } from "./routes/badge";
import { BreadcrumbPage } from "./routes/breadcrumb";
import { BubblePage } from "./routes/bubble";
import { ButtonPage } from "./routes/button";
import { ButtonGroupPage } from "./routes/button-group";
import { CalendarPage } from "./routes/calendar";
import { CardPage } from "./routes/card";
import { CardCounterPage } from "./routes/card-counter";
import { CarouselPage } from "./routes/carousel";
import { ChartPage } from "./routes/chart";
import { CheckboxPage } from "./routes/checkbox";
import { CollapsiblePage } from "./routes/collapsible";
import { ComboboxPage } from "./routes/combobox";
import { CommandPage } from "./routes/command";
import { ContextMenuPage } from "./routes/context-menu";
import { DialogPage } from "./routes/dialog";
import { DirectionPage } from "./routes/direction";
import { DrawerPage } from "./routes/drawer";
import { DropdownMenuPage } from "./routes/dropdown-menu";
import { EmptyPage } from "./routes/empty";
import { FieldPage } from "./routes/field";
import { FormPage } from "./routes/form";
import { HoverCardPage } from "./routes/hover-card";
import { InputPage } from "./routes/input";
import { InputGroupPage } from "./routes/input-group";
import { InputOtpPage } from "./routes/input-otp";
import { ItemPage } from "./routes/item";
import { KbdPage } from "./routes/kbd";
import { LabelPage } from "./routes/label";
import { MarkerPage } from "./routes/marker";
import { MenubarPage } from "./routes/menubar";
import { MessagePage } from "./routes/message";
import { MessageScrollerPage } from "./routes/message-scroller";
import { NativeSelectPage } from "./routes/native-select";
import { NavigationMenuPage } from "./routes/navigation-menu";
import { PaginationPage } from "./routes/pagination";
import { PopoverPage } from "./routes/popover";
import { ProgressPage } from "./routes/progress";
import { RadioGroupPage } from "./routes/radio-group";
import { ResizablePage } from "./routes/resizable";
import { ScrollAreaPage } from "./routes/scroll-area";
import { SelectPage } from "./routes/select";
import { SeparatorPage } from "./routes/separator";
import { SheetPage } from "./routes/sheet";
import { SidebarPage } from "./routes/sidebar";
import { SkeletonPage } from "./routes/skeleton";
import { SliderPage } from "./routes/slider";
import { SonnerPage } from "./routes/sonner";
import { SpinnerPage } from "./routes/spinner";
import { SwitchPage } from "./routes/switch";
import { TablePage } from "./routes/table";
import { TabsPage } from "./routes/tabs";
import { TextareaPage } from "./routes/textarea";
import { TogglePage } from "./routes/toggle";
import { ToggleGroupPage } from "./routes/toggle-group";
import { TooltipPage } from "./routes/tooltip";

const rootRoute = createRootRoute({
  component: () => (
    <div className="min-h-screen bg-background text-foreground">
      <div className="flex">
        <aside className="sticky top-0 h-screen w-56 shrink-0 overflow-y-auto border-r p-4">
          <Link to="/" className="text-base font-semibold text-foreground">
            @akagiyui/ui-react
          </Link>
          <nav className="mt-4 flex flex-col gap-0.5 text-sm">
            <Link
              key="accordion"
              to={`/accordion`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              accordion
            </Link>
            <Link
              key="alert"
              to={`/alert`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              alert
            </Link>
            <Link
              key="alert-dialog"
              to={`/alert-dialog`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              alert-dialog
            </Link>
            <Link
              key="aspect-ratio"
              to={`/aspect-ratio`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              aspect-ratio
            </Link>
            <Link
              key="attachment"
              to={`/attachment`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              attachment
            </Link>
            <Link
              key="avatar"
              to={`/avatar`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              avatar
            </Link>
            <Link
              key="badge"
              to={`/badge`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              badge
            </Link>
            <Link
              key="breadcrumb"
              to={`/breadcrumb`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              breadcrumb
            </Link>
            <Link
              key="bubble"
              to={`/bubble`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              bubble
            </Link>
            <Link
              key="button"
              to={`/button`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              button
            </Link>
            <Link
              key="button-group"
              to={`/button-group`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              button-group
            </Link>
            <Link
              key="calendar"
              to={`/calendar`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              calendar
            </Link>
            <Link
              key="card"
              to={`/card`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              card
            </Link>
            <Link
              key="card-counter"
              to={`/card-counter`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              card-counter
            </Link>
            <Link
              key="carousel"
              to={`/carousel`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              carousel
            </Link>
            <Link
              key="chart"
              to={`/chart`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              chart
            </Link>
            <Link
              key="checkbox"
              to={`/checkbox`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              checkbox
            </Link>
            <Link
              key="collapsible"
              to={`/collapsible`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              collapsible
            </Link>
            <Link
              key="combobox"
              to={`/combobox`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              combobox
            </Link>
            <Link
              key="command"
              to={`/command`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              command
            </Link>
            <Link
              key="context-menu"
              to={`/context-menu`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              context-menu
            </Link>
            <Link
              key="dialog"
              to={`/dialog`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              dialog
            </Link>
            <Link
              key="direction"
              to={`/direction`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              direction
            </Link>
            <Link
              key="drawer"
              to={`/drawer`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              drawer
            </Link>
            <Link
              key="dropdown-menu"
              to={`/dropdown-menu`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              dropdown-menu
            </Link>
            <Link
              key="empty"
              to={`/empty`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              empty
            </Link>
            <Link
              key="field"
              to={`/field`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              field
            </Link>
            <Link
              key="form"
              to={`/form`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              form
            </Link>
            <Link
              key="hover-card"
              to={`/hover-card`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              hover-card
            </Link>
            <Link
              key="input"
              to={`/input`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              input
            </Link>
            <Link
              key="input-group"
              to={`/input-group`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              input-group
            </Link>
            <Link
              key="input-otp"
              to={`/input-otp`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              input-otp
            </Link>
            <Link
              key="item"
              to={`/item`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              item
            </Link>
            <Link
              key="kbd"
              to={`/kbd`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              kbd
            </Link>
            <Link
              key="label"
              to={`/label`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              label
            </Link>
            <Link
              key="marker"
              to={`/marker`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              marker
            </Link>
            <Link
              key="menubar"
              to={`/menubar`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              menubar
            </Link>
            <Link
              key="message"
              to={`/message`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              message
            </Link>
            <Link
              key="message-scroller"
              to={`/message-scroller`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              message-scroller
            </Link>
            <Link
              key="native-select"
              to={`/native-select`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              native-select
            </Link>
            <Link
              key="navigation-menu"
              to={`/navigation-menu`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              navigation-menu
            </Link>
            <Link
              key="pagination"
              to={`/pagination`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              pagination
            </Link>
            <Link
              key="popover"
              to={`/popover`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              popover
            </Link>
            <Link
              key="progress"
              to={`/progress`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              progress
            </Link>
            <Link
              key="radio-group"
              to={`/radio-group`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              radio-group
            </Link>
            <Link
              key="resizable"
              to={`/resizable`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              resizable
            </Link>
            <Link
              key="scroll-area"
              to={`/scroll-area`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              scroll-area
            </Link>
            <Link
              key="select"
              to={`/select`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              select
            </Link>
            <Link
              key="separator"
              to={`/separator`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              separator
            </Link>
            <Link
              key="sheet"
              to={`/sheet`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              sheet
            </Link>
            <Link
              key="sidebar"
              to={`/sidebar`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              sidebar
            </Link>
            <Link
              key="skeleton"
              to={`/skeleton`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              skeleton
            </Link>
            <Link
              key="slider"
              to={`/slider`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              slider
            </Link>
            <Link
              key="sonner"
              to={`/sonner`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              sonner
            </Link>
            <Link
              key="spinner"
              to={`/spinner`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              spinner
            </Link>
            <Link
              key="switch"
              to={`/switch`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              switch
            </Link>
            <Link
              key="table"
              to={`/table`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              table
            </Link>
            <Link
              key="tabs"
              to={`/tabs`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              tabs
            </Link>
            <Link
              key="textarea"
              to={`/textarea`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              textarea
            </Link>
            <Link
              key="toggle"
              to={`/toggle`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              toggle
            </Link>
            <Link
              key="toggle-group"
              to={`/toggle-group`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              toggle-group
            </Link>
            <Link
              key="tooltip"
              to={`/tooltip`}
              className="rounded px-2 py-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              activeProps={{ className: "bg-accent text-foreground" }}
            >
              tooltip
            </Link>
          </nav>
        </aside>
        <div className="flex-1 min-w-0">
          <header className="flex items-center justify-end border-b px-6 py-3">
            <ThemeToggle />
          </header>
          <main className="mx-auto max-w-5xl px-6 py-10">
            <Outlet />
          </main>
        </div>
      </div>
      <Toaster richColors position="bottom-right" />
    </div>
  ),
});

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/",
  component: IndexPage,
});

const AccordionRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/accordion",
  component: AccordionPage,
});

const AlertRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/alert",
  component: AlertPage,
});

const AlertDialogRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/alert-dialog",
  component: AlertDialogPage,
});

const AspectRatioRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/aspect-ratio",
  component: AspectRatioPage,
});

const AttachmentRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/attachment",
  component: AttachmentPage,
});

const AvatarRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/avatar",
  component: AvatarPage,
});

const BadgeRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/badge",
  component: BadgePage,
});

const BreadcrumbRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/breadcrumb",
  component: BreadcrumbPage,
});

const BubbleRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/bubble",
  component: BubblePage,
});

const ButtonRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/button",
  component: ButtonPage,
});

const ButtonGroupRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/button-group",
  component: ButtonGroupPage,
});

const CalendarRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/calendar",
  component: CalendarPage,
});

const CardRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/card",
  component: CardPage,
});

const CardCounterRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/card-counter",
  component: CardCounterPage,
});

const CarouselRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/carousel",
  component: CarouselPage,
});

const ChartRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/chart",
  component: ChartPage,
});

const CheckboxRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/checkbox",
  component: CheckboxPage,
});

const CollapsibleRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/collapsible",
  component: CollapsiblePage,
});

const ComboboxRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/combobox",
  component: ComboboxPage,
});

const CommandRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/command",
  component: CommandPage,
});

const ContextMenuRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/context-menu",
  component: ContextMenuPage,
});

const DialogRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/dialog",
  component: DialogPage,
});

const DirectionRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/direction",
  component: DirectionPage,
});

const DrawerRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/drawer",
  component: DrawerPage,
});

const DropdownMenuRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/dropdown-menu",
  component: DropdownMenuPage,
});

const EmptyRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/empty",
  component: EmptyPage,
});

const FieldRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/field",
  component: FieldPage,
});

const FormRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/form",
  component: FormPage,
});

const HoverCardRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/hover-card",
  component: HoverCardPage,
});

const InputRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/input",
  component: InputPage,
});

const InputGroupRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/input-group",
  component: InputGroupPage,
});

const InputOtpRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/input-otp",
  component: InputOtpPage,
});

const ItemRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/item",
  component: ItemPage,
});

const KbdRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/kbd",
  component: KbdPage,
});

const LabelRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/label",
  component: LabelPage,
});

const MarkerRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/marker",
  component: MarkerPage,
});

const MenubarRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/menubar",
  component: MenubarPage,
});

const MessageRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/message",
  component: MessagePage,
});

const MessageScrollerRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/message-scroller",
  component: MessageScrollerPage,
});

const NativeSelectRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/native-select",
  component: NativeSelectPage,
});

const NavigationMenuRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/navigation-menu",
  component: NavigationMenuPage,
});

const PaginationRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/pagination",
  component: PaginationPage,
});

const PopoverRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/popover",
  component: PopoverPage,
});

const ProgressRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/progress",
  component: ProgressPage,
});

const RadioGroupRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/radio-group",
  component: RadioGroupPage,
});

const ResizableRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/resizable",
  component: ResizablePage,
});

const ScrollAreaRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/scroll-area",
  component: ScrollAreaPage,
});

const SelectRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/select",
  component: SelectPage,
});

const SeparatorRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/separator",
  component: SeparatorPage,
});

const SheetRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/sheet",
  component: SheetPage,
});

const SidebarRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/sidebar",
  component: SidebarPage,
});

const SkeletonRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/skeleton",
  component: SkeletonPage,
});

const SliderRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/slider",
  component: SliderPage,
});

const SonnerRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/sonner",
  component: SonnerPage,
});

const SpinnerRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/spinner",
  component: SpinnerPage,
});

const SwitchRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/switch",
  component: SwitchPage,
});

const TableRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/table",
  component: TablePage,
});

const TabsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/tabs",
  component: TabsPage,
});

const TextareaRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/textarea",
  component: TextareaPage,
});

const ToggleRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/toggle",
  component: TogglePage,
});

const ToggleGroupRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/toggle-group",
  component: ToggleGroupPage,
});

const TooltipRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/tooltip",
  component: TooltipPage,
});

const routeTree = rootRoute.addChildren([
  indexRoute,
  AccordionRoute,
  AlertRoute,
  AlertDialogRoute,
  AspectRatioRoute,
  AttachmentRoute,
  AvatarRoute,
  BadgeRoute,
  BreadcrumbRoute,
  BubbleRoute,
  ButtonRoute,
  ButtonGroupRoute,
  CalendarRoute,
  CardRoute,
  CardCounterRoute,
  CarouselRoute,
  ChartRoute,
  CheckboxRoute,
  CollapsibleRoute,
  ComboboxRoute,
  CommandRoute,
  ContextMenuRoute,
  DialogRoute,
  DirectionRoute,
  DrawerRoute,
  DropdownMenuRoute,
  EmptyRoute,
  FieldRoute,
  FormRoute,
  HoverCardRoute,
  InputRoute,
  InputGroupRoute,
  InputOtpRoute,
  ItemRoute,
  KbdRoute,
  LabelRoute,
  MarkerRoute,
  MenubarRoute,
  MessageRoute,
  MessageScrollerRoute,
  NativeSelectRoute,
  NavigationMenuRoute,
  PaginationRoute,
  PopoverRoute,
  ProgressRoute,
  RadioGroupRoute,
  ResizableRoute,
  ScrollAreaRoute,
  SelectRoute,
  SeparatorRoute,
  SheetRoute,
  SidebarRoute,
  SkeletonRoute,
  SliderRoute,
  SonnerRoute,
  SpinnerRoute,
  SwitchRoute,
  TableRoute,
  TabsRoute,
  TextareaRoute,
  ToggleRoute,
  ToggleGroupRoute,
  TooltipRoute,
]);

export const router = createRouter({ routeTree });

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
