/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */
import { Link } from "@tanstack/react-router";

export function IndexPage() {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-foreground">@akagiyui/ui-react</h1>
        <p className="mt-2 text-muted-foreground">
          基于 shadcn (new-york) 的个人 React 组件库。支持 npm 包与 registry 双模消费。
        </p>
      </div>
      <div className="grid gap-4 sm:grid-cols-2">
      <Link
        key="accordion"
        to="/accordion"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Accordion</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/accordion</code>
      </Link>
      <Link
        key="alert"
        to="/alert"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Alert</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/alert</code>
      </Link>
      <Link
        key="alert-dialog"
        to="/alert-dialog"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">AlertDialog</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/alert-dialog</code>
      </Link>
      <Link
        key="aspect-ratio"
        to="/aspect-ratio"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">AspectRatio</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/aspect-ratio</code>
      </Link>
      <Link
        key="attachment"
        to="/attachment"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Attachment</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/attachment</code>
      </Link>
      <Link
        key="avatar"
        to="/avatar"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Avatar</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/avatar</code>
      </Link>
      <Link
        key="badge"
        to="/badge"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Badge</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/badge</code>
      </Link>
      <Link
        key="breadcrumb"
        to="/breadcrumb"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Breadcrumb</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/breadcrumb</code>
      </Link>
      <Link
        key="bubble"
        to="/bubble"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Bubble</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/bubble</code>
      </Link>
      <Link
        key="button"
        to="/button"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Button</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/button</code>
      </Link>
      <Link
        key="button-group"
        to="/button-group"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">ButtonGroup</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/button-group</code>
      </Link>
      <Link
        key="calendar"
        to="/calendar"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Calendar</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/calendar</code>
      </Link>
      <Link
        key="card"
        to="/card"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Card</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/card</code>
      </Link>
      <Link
        key="card-counter"
        to="/card-counter"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">CardCounter</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/card-counter</code>
      </Link>
      <Link
        key="carousel"
        to="/carousel"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Carousel</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/carousel</code>
      </Link>
      <Link
        key="chart"
        to="/chart"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Chart</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/chart</code>
      </Link>
      <Link
        key="checkbox"
        to="/checkbox"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Checkbox</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/checkbox</code>
      </Link>
      <Link
        key="collapsible"
        to="/collapsible"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Collapsible</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/collapsible</code>
      </Link>
      <Link
        key="combobox"
        to="/combobox"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Combobox</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/combobox</code>
      </Link>
      <Link
        key="command"
        to="/command"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Command</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/command</code>
      </Link>
      <Link
        key="context-menu"
        to="/context-menu"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">ContextMenu</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/context-menu</code>
      </Link>
      <Link
        key="dialog"
        to="/dialog"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Dialog</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/dialog</code>
      </Link>
      <Link
        key="direction"
        to="/direction"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Direction</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/direction</code>
      </Link>
      <Link
        key="drawer"
        to="/drawer"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Drawer</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/drawer</code>
      </Link>
      <Link
        key="dropdown-menu"
        to="/dropdown-menu"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">DropdownMenu</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/dropdown-menu</code>
      </Link>
      <Link
        key="empty"
        to="/empty"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Empty</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/empty</code>
      </Link>
      <Link
        key="field"
        to="/field"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Field</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/field</code>
      </Link>
      <Link
        key="form"
        to="/form"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Form</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/form</code>
      </Link>
      <Link
        key="hover-card"
        to="/hover-card"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">HoverCard</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/hover-card</code>
      </Link>
      <Link
        key="icons"
        to="/icons"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Icons</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/icons</code>
      </Link>
      <Link
        key="input"
        to="/input"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Input</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/input</code>
      </Link>
      <Link
        key="input-group"
        to="/input-group"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">InputGroup</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/input-group</code>
      </Link>
      <Link
        key="input-otp"
        to="/input-otp"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">InputOtp</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/input-otp</code>
      </Link>
      <Link
        key="item"
        to="/item"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Item</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/item</code>
      </Link>
      <Link
        key="kbd"
        to="/kbd"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Kbd</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/kbd</code>
      </Link>
      <Link
        key="label"
        to="/label"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Label</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/label</code>
      </Link>
      <Link
        key="marker"
        to="/marker"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Marker</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/marker</code>
      </Link>
      <Link
        key="menubar"
        to="/menubar"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Menubar</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/menubar</code>
      </Link>
      <Link
        key="message"
        to="/message"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Message</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/message</code>
      </Link>
      <Link
        key="message-scroller"
        to="/message-scroller"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">MessageScroller</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/message-scroller</code>
      </Link>
      <Link
        key="native-select"
        to="/native-select"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">NativeSelect</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/native-select</code>
      </Link>
      <Link
        key="navigation-menu"
        to="/navigation-menu"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">NavigationMenu</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/navigation-menu</code>
      </Link>
      <Link
        key="pagination"
        to="/pagination"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Pagination</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/pagination</code>
      </Link>
      <Link
        key="popover"
        to="/popover"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Popover</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/popover</code>
      </Link>
      <Link
        key="progress"
        to="/progress"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Progress</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/progress</code>
      </Link>
      <Link
        key="radio-group"
        to="/radio-group"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">RadioGroup</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/radio-group</code>
      </Link>
      <Link
        key="resizable"
        to="/resizable"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Resizable</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/resizable</code>
      </Link>
      <Link
        key="scroll-area"
        to="/scroll-area"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">ScrollArea</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/scroll-area</code>
      </Link>
      <Link
        key="select"
        to="/select"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Select</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/select</code>
      </Link>
      <Link
        key="separator"
        to="/separator"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Separator</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/separator</code>
      </Link>
      <Link
        key="sheet"
        to="/sheet"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Sheet</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/sheet</code>
      </Link>
      <Link
        key="sidebar"
        to="/sidebar"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Sidebar</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/sidebar</code>
      </Link>
      <Link
        key="skeleton"
        to="/skeleton"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Skeleton</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/skeleton</code>
      </Link>
      <Link
        key="slider"
        to="/slider"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Slider</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/slider</code>
      </Link>
      <Link
        key="sonner"
        to="/sonner"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Sonner</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/sonner</code>
      </Link>
      <Link
        key="spinner"
        to="/spinner"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Spinner</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/spinner</code>
      </Link>
      <Link
        key="switch"
        to="/switch"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Switch</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/switch</code>
      </Link>
      <Link
        key="table"
        to="/table"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Table</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/table</code>
      </Link>
      <Link
        key="tabs"
        to="/tabs"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Tabs</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/tabs</code>
      </Link>
      <Link
        key="textarea"
        to="/textarea"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Textarea</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/textarea</code>
      </Link>
      <Link
        key="toggle"
        to="/toggle"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Toggle</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/toggle</code>
      </Link>
      <Link
        key="toggle-group"
        to="/toggle-group"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">ToggleGroup</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/toggle-group</code>
      </Link>
      <Link
        key="tooltip"
        to="/tooltip"
        className="block rounded-lg border bg-card p-5 text-card-foreground shadow-sm transition-colors hover:bg-accent"
      >
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Tooltip</h2>
          <span className="rounded bg-secondary px-2 py-0.5 text-xs font-mono text-secondary-foreground">registry:ui</span>
        </div>
        <p className="mt-2 text-sm text-muted-foreground">shadcn new-york 组件。</p>
        <code className="mt-3 block rounded bg-muted px-2 py-1 text-xs text-muted-foreground">npx shadcn@latest add @akagiyui/tooltip</code>
      </Link>
      </div>
    </div>
  );
}
