/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */
import { Markdown } from "../components/markdown";
import { ComponentGrid } from "../components/component-grid";
import { componentGroups } from "../components/component-groups";
import readme from "../../../lib-ui-react/README.md?raw";

export function IndexPage() {
  return (
    <div className="space-y-10">
      <Markdown content={readme} />
      <ComponentGrid groups={componentGroups} />
    </div>
  );
}
