/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */
import { DemoRenderer } from "../components/demo-renderer";
import { CodeBlock } from "../components/code-block";
import source from "../../../lib-ui-react/src/components/ui/item.tsx?raw";

export function ItemPage() {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-bold">Item</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          registry:ui · shadcn new-york 组件，支持 <code>npx shadcn add</code> 拉取。
        </p>
      </div>
      <section className="space-y-3">
        <h2 className="text-lg font-semibold">预览</h2>
        <div className="rounded-lg border bg-card p-6 text-card-foreground">
          <DemoRenderer name="item" />
        </div>
      </section>
      <section className="space-y-3">
        <h2 className="text-lg font-semibold">源码</h2>
        <CodeBlock code={source} />
      </section>
      <section className="space-y-3">
        <h2 className="text-lg font-semibold">安装</h2>
        <CodeBlock code={"npx shadcn@latest add @akagiyui/item"} lang="bash" />
      </section>
    </div>
  );
}
