/** AUTO-GENERATED by lib-ui-react/scripts/gen.mjs */
import { DemoRenderer } from "../components/demo-renderer";
import source from "../../../lib-ui-react/src/components/ui/sheet.tsx?raw";

export function SheetPage() {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-bold">Sheet</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          registry:ui · shadcn new-york 组件，支持 <code>npx shadcn add</code> 拉取。
        </p>
      </div>
      <section className="space-y-3">
        <h2 className="text-lg font-semibold">预览</h2>
        <div className="rounded-lg border bg-card p-6 text-card-foreground">
          <DemoRenderer name="sheet" />
        </div>
      </section>
      <section className="space-y-3">
        <h2 className="text-lg font-semibold">源码</h2>
        <pre className="overflow-x-auto rounded-lg bg-muted p-4 text-sm text-muted-foreground">
          <code>{source}</code>
        </pre>
      </section>
      <section className="space-y-3">
        <h2 className="text-lg font-semibold">安装</h2>
        <code className="block rounded-lg bg-muted p-4 text-sm text-muted-foreground">
          npx shadcn@latest add @akagiyui/sheet
        </code>
      </section>
    </div>
  );
}
